# Generated by Django 5.2.6 on 2025-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('ar', 'Arabic'), ('de', 'German'), ('fr', 'French')], default='en', max_length=10),
        ),
    ]
